"$schema" = 'https://starship.rs/config-schema.json'

# A minimal left prompt
format = """
$directory\
$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """$all"""

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = true
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = false
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
# style = "fg:mantle bg:peach"
format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"

[directory.substitutions]
"~/Downloads" = " "
"Pictures" = " "

# [git_branch]
# symbol = ""
# style = "bg:teal"
# format = '[[ $symbol $branch ](green)]($style)'

[git_branch]
symbol = ""
style = "bg:teal"
format =  '[$symbol $branch(:$remote_branch)]($style)'

[git_status]
# style = "teal"
format = '[($all_status$ahead_behind )]($style)'

# [aws]
# format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
# disabled = true

[nodejs]
symbol = ""
# style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[c]
symbol = " "
# style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[rust]
symbol = ""
# style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[golang]
symbol = ""
# style = "bg:teal"
format = '[[ $symbol( $version) ](teal)]($style)'

[php]
symbol = ""
# style = "bg:teal"
format = '[[ $symbol( $version) ](teal)]($style)'

[java]
symbol = " "
# style = "bg:teal"
format = '[[ $symbol( $version) ](teal)]($style)'

[kotlin]
symbol = ""
# style = "bg:teal"
format = '[[ $symbol( $version) ](teal)]($style)'

[haskell]
symbol = ""
# style = "bg:teal"
format = '[[ $symbol( $version) ](teal)]($style)'

[python]
symbol = ""
# style = "bg:teal"
format = '[[ $symbol( $version) ](teal)]($style)'

[docker_context]
disabled = true
symbol = ""
# style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

# [time]
# disabled = true
# time_format = "%R"
# # style = "bg:peach"
# format = '[[  $time ](fg:mantle bg:purple)]($style)'

[kubernetes]
symbol = '☸ '
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "k3d-management-cluster", style = "green", context_alias = "[local] k3d", symbol = "" },
  { context_pattern = "capi-csre-plat-preprod-br-se1-yel-1", style = "yellow", context_alias = "[undercloud] preprod|dev-qa", symbol = "" },  
  { context_pattern = "capi-csre-plat-prod-br-se1-yel-1", style = "red", context_alias = "[undercloud] PROD", symbol = " " },
  { context_pattern = "eks-prod", style = "red", context_alias = "PROD", symbol = " " },
  { context_pattern = "eks-qa", style = "green", context_alias = "QA", symbol = " " },
]

[aws]
disabled = true
profile_aliases = { "platform-qa" = "qa",  "platform-prod" = "prod" }

[lua]
disabled = true

[gcloud]
disabled = true



[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'