[tools]
argocd = "latest"
aws = { version = "latest", symlink_bins = "true" }
aws-cli = "latest"
bat = "latest"
btop = "latest"
claude = "latest"
clusterctl = "1.14.1"
codex = "latest"
docker-cli = "latest"
dotnet = "latest"
eza = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
go = "1.27.1"
helm = "latest"
k3d = "latest"
k9s = "latest"
kubectl = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
npm = "latest"
oha = "latest"
poetry = "latest"
starship = "latest"
stern = "latest"
terraform = "latest"
terragrunt = "1.1.4"
tilt = "latest"
tmux = "3.7c"
vault = "latest"
velero = "latest"
yazi = "latest"
yq = "latest"
zoxide = "latest"
